version: "3"

services:
   pc_group_membership_manager:
      build: .
      restart: unless-stopped
      environment:
         DELAY: ${DELAY-20s}
         CALDAV_PRINCIPAL_URL: ${CALDAV_PRINCIPAL_URL}
         CALDAV_USERNAME: ${CALDAV_USERNAME}
         CALDAV_PASSWORD: ${CALDAV_PASSWORD}
         SERVICE_BOX_CALENDAR_NAME: ${SERVICE_BOX_CALENDAR_NAME}
         ALLOWING_LDAP_GROUP_NAME: ${ALLOWING_LDAP_GROUP_NAME}
         SHELL_DEBUG: ${SHELL_DEBUG:-}
         TEST_ICS_URL_LIST: ${TEST_ICS_URL_LIST}
      volumes:
         - ./dsrc.txt:/data/config/container.inf:ro
         - ./pwdfile.txt:/etc/pwdfile.txt:ro
      command:
         - bash
         - -c
         - 'while true; do echo "INFO: $$( date )" 1>&2; /code/bin/updateGroupsFromAppointements.sh; echo "INFO: ==================== Next check in $${DELAY} ====================" 1>&2; sleep $${DELAY}; done'
      networks:
         - internal_services

networks:

   internal_services:
      external: true
      name: internal_services
