version: "3"

services:
   pc_group_membership_manager:
      build: .
      environment:
         - DELAY=1m
      volumes:
         - ./dav_config.env:/code/dav_config.env:ro
         - ./dsrc.txt:/data/config/container.inf:ro
         - ./pwdfile.txt:/etc/pwdfile.txt:ro
      command:
         - bash
         - -c
         - while true; do /code/bin/updateGroupsFromAppointements.sh; echo "==== Next check in $${DELAY}"; date; sleep $${DELAY}; done
      networks:
         - internal_services

networks:

   internal_services:
      external:
         name: internal_services
